# MKSurvival Configuration - Comprehensive RPG System
# Version: 2.0 - Full Implementation

# ===========================================
# ECONOMY SYSTEM CONFIGURATION
# ===========================================
economy:
  starting_balance: 1000.0
  max_balance: 10000000.0
  currency_symbol: "⭐"
  currency_name_singular: "moneda"
  currency_name_plural: "monedas"
  
  # Interest and banking
  daily_interest_rate: 0.02  # 2% daily
  max_interest_amount: 5000.0
  
  # Transaction fees
  transfer_fee_percentage: 0.01  # 1%
  min_transfer_fee: 1.0
  max_transfer_fee: 100.0
  
  # Economy activities
  mob_kill_rewards:
    ZOMBIE: 2.0
    SKELETON: 3.0
    CREEPER: 5.0
    SPIDER: 2.5
    ENDERMAN: 15.0
    WITHER_SKELETON: 25.0
  
  mining_rewards:
    COAL_ORE: 1.0
    IRON_ORE: 3.0
    GOLD_ORE: 5.0
    DIAMOND_ORE: 20.0
    EMERALD_ORE: 15.0
    ANCIENT_DEBRIS: 50.0
  
  # Shop multipliers
  buy_price_multiplier: 1.5
  sell_price_multiplier: 0.6

# ===========================================
# SKILL SYSTEM CONFIGURATION
# ===========================================
skills:
  enable_level_up_effects: true
  max_level: 100
  exp_curve_multiplier: 1.2
  
  # Skill progression settings
  base_exp_required: 100
  exp_curve_power: 1.5
  
  # Skill bonuses
  bonus_chance_per_level: 0.01  # 1% per level
  max_bonus_chance: 0.5  # 50% max
  
  # Double drop chances
  double_drop_base_chance: 0.05
  double_drop_level_bonus: 0.002
  
  # Experience sources
  experience_sources:
    MINING:
      STONE: 1
      COAL_ORE: 3
      IRON_ORE: 5
      GOLD_ORE: 8
      DIAMOND_ORE: 15
      EMERALD_ORE: 12
    COMBAT:
      ZOMBIE: 2
      SKELETON: 3
      CREEPER: 4
      SPIDER: 2
      ENDERMAN: 10
    ALCHEMY:
      POTION_BREW: 5
      ENCHANT_ITEM: 3
    FORAGING:
      TREE_CUT: 1
      CROP_HARVEST: 1

# ===========================================
# QUEST SYSTEM CONFIGURATION
# ===========================================
quests:
  max_active_quests: 8
  daily_quest_limit: 5
  weekly_quest_limit: 3
  
  # Dynamic quest generation
  dynamic_quests:
    enable: true
    generation_interval: 300  # 5 minutes
    max_generated_per_player: 10
    difficulty_scaling: true
    
  # Quest rewards scaling
  reward_multipliers:
    easy: 1.0
    medium: 1.5
    hard: 2.0
    epic: 3.0
    legendary: 5.0
  
  # Quest completion bonuses
  completion_streak_bonus: 0.1  # 10% per consecutive day
  max_streak_bonus: 1.0  # 100% max

# ===========================================
# BOSS SYSTEM CONFIGURATION
# ===========================================
bosses:
  enable: true
  spawn_interval_minutes: 60
  max_concurrent_bosses: 3
  
  # Boss scaling
  health_per_player: 200
  damage_per_player: 5
  
  # Announcement settings
  announce_spawn: true
  announce_death: true
  announcement_radius: 100
  
  # Rewards
  participant_reward_threshold: 0.1  # 10% damage to get rewards
  
# ===========================================
# DUNGEON SYSTEM CONFIGURATION
# ===========================================
dungeons:
  enable: true
  max_players_per_dungeon: 6
  instance_cleanup_time: 300  # 5 minutes
  
  # Difficulty scaling
  scale_with_players: true
  health_multiplier_per_player: 1.3
  
  # Rewards
  completion_bonus: 0.2  # 20% bonus for completion
  speed_bonus_threshold: 600  # 10 minutes for speed bonus
  
# ===========================================
# PET SYSTEM CONFIGURATION
# ===========================================
pets:
  enable: true
  max_pets_per_player: 3
  
  # Breeding system
  breeding_cooldown: 86400  # 24 hours
  breeding_cost: 500.0
  mutation_chance: 0.05  # 5%
  
  # Evolution system
  evolution_level_requirement: 25
  evolution_cost_multiplier: 2.0
  
  # Competition system
  competitions:
    enable: true
    daily_competitions: 2
    entry_fee: 100.0
    prize_pool_multiplier: 0.8  # 80% of entry fees

# ===========================================
# FACTION SYSTEM CONFIGURATION
# ===========================================
factions:
  enable: true
  max_members: 20
  max_allies: 5
  max_enemies: 10
  
  # Costs
  creation_cost: 5000.0
  claim_cost: 1000.0
  
  # Power system
  power_per_player: 10
  power_loss_per_death: 2
  power_regen_per_hour: 1
  max_power_loss: 50
  
  # Wars
  war_declaration_cost: 2000.0
  war_duration_hours: 24
  war_cooldown_hours: 48

# ===========================================
# LAND PROTECTION CONFIGURATION
# ===========================================
land:
  enable_claims: true
  starting_claim_blocks: 200
  max_claims_per_player: 5
  claim_block_cost: 10.0
  allow_wilderness_building: true
  
  # Claim growth
  blocks_per_hour_played: 1
  max_total_blocks: 5000
  
  # Protection settings
  protect_from_explosions: true
  protect_from_fire: true
  protect_from_mobs: true

# ===========================================
# RANKING SYSTEM CONFIGURATION
# ===========================================
rankings:
  enable: true
  update_interval_minutes: 5
  
  # Seasonal system
  seasons:
    enable: true
    season_length_days: 30
    seasonal_rewards: true
    
  # Competitions
  competitions:
    enable: true
    weekly_competitions: true
    daily_competitions: true
    
# ===========================================
# GUI SYSTEM CONFIGURATION
# ===========================================
gui:
  # GUI titles (using MiniMessage format)
  titles:
    skills: "<gold>Skills RPG</gold>"
    quests: "<green>Misiones Activas</green>"
    classes: "<blue>Selección de Clase</blue>"
    shop: "<yellow>Tienda del Servidor</yellow>"
    pets: "<pink>Mis Mascotas</pink>"
    factions: "<red>Sistema de Facciones</red>"
    dungeons: "<dark_purple>Mazmorras Disponibles</dark_purple>"
    rankings: "<gold>Rankings del Servidor</gold>"
    specializations: "<aqua>Especializaciones</aqua>"
  
  # Auto-refresh intervals (in ticks)
  refresh_intervals:
    skills: 100
    quests: 60
    rankings: 200
    
  # GUI sizes
  sizes:
    skills: 45
    quests: 54
    classes: 27
    shop: 54
    pets: 45

# ===========================================
# CLASS SYSTEM CONFIGURATION
# ===========================================
classes:
  enable_classes: true
  default_class: "adventurer"
  allow_class_change: true
  class_change_cost: 1000.0
  class_change_cooldown: 86400  # 24 hours
  
  # Class bonuses
  bonus_multipliers:
    warrior: 
      combat_damage: 1.2
      health_regen: 1.1
    archer:
      ranged_damage: 1.3
      movement_speed: 1.1
    mage:
      magic_damage: 1.4
      mana_regen: 1.2
    adventurer:
      experience_gain: 1.1
      luck: 1.05

# ===========================================
# ITEM QUALITY SYSTEM
# ===========================================
item_quality:
  enable: true
  chance_per_quality_level: 0.1  # 10% chance for upgrades
  max_quality_level: 5
  
  # Quality effects
  damage_multiplier_per_level: 0.1  # 10% per level
  durability_multiplier_per_level: 0.15  # 15% per level
  
# ===========================================
# ACHIEVEMENT SYSTEM
# ===========================================
achievements:
  enable: true
  broadcast_unlocks: true
  achievement_points_reward: 100.0
  
  # Special achievements
  first_login_reward: 500.0
  playtime_milestones: [3600, 7200, 18000, 36000]  # 1h, 2h, 5h, 10h
  
# ===========================================
# WORLD SETTINGS
# ===========================================
worlds:
  # Enabled worlds for the plugin
  enabled_worlds:
    - "world"
    - "world_nether"
    - "world_the_end"
  
  # World-specific settings
  world_settings:
    world:
      allow_pvp: true
      skill_experience_multiplier: 1.0
      quest_generation: true
    world_nether:
      allow_pvp: true
      skill_experience_multiplier: 1.5
      quest_generation: true
    world_the_end:
      allow_pvp: true
      skill_experience_multiplier: 2.0
      quest_generation: false

# ===========================================
# PERFORMANCE SETTINGS
# ===========================================
performance:
  # Database save intervals (in ticks)
  auto_save_interval: 6000  # 5 minutes
  
  # Cache settings
  cache_player_data: true
  cache_size_limit: 1000
  
  # Async processing
  async_database_operations: true
  async_calculation_threshold: 100
  
# ===========================================
# DEBUG AND LOGGING
# ===========================================
debug: false
verbose_logging: false
log_level: "INFO"  # DEBUG, INFO, WARN, ERROR

# Development settings
development:
  enable_test_commands: false
  bypass_cooldowns: false
  unlimited_resources: false